export default {
    GET_SCHEDULE:"GET_SCHEDULE",
    GET_SCHEDULE_FETCHING:"GET_SCHEDULE_FETCHING",
    GET_SCHEDULE_RESOLVE:"GET_SCHEDULE_RESOLVE",
    GET_SCHEDULE_REJECT:"GET_SCHEDULE_REJECT"  
 }  