export default {
    GET_SCHEDULE:"GET_SCHEDULE",
    GET_SCHEDULE_FETCHING:"GET_SCHEDULE_FETCHING",
    GET_SCHEDULE_RESOLVE:"GET_SCHEDULE_RESOLVE",
    GET_SCHEDULE_REJECT:"GET_SCHEDULE_REJECT" ,

    GET_ALL_PRODUCTS:"GET_ALL_PRODUCTS",
    GET_PRODUCTS_FETCHING:"GET_PRODUCTS_FETCHING",
    GET_PRODUCTS_RESOLVE:"GET_PRUCTS_RESOLVE",
    GET_PRODUCTS_REJECT:"GET_PRODUCTS_REJECT",
    GET_PRODUCT_DETAILS:"GET_PRODUCT_DETAILS",
    CLEAR_PRODUCT_DETAILS:"CLEAR_PRODUCT_DETAILS"
 }  